services:
  - type: web
    name: vapor-backend
    plan: free
    env: docker
    autoDeploy: true
    buildCommand: "" # Docker cuida disso
    startCommand: "" # idem

    envVars:
      - key: PORT
        value: 8080
      - key: POSTGRES_HOST
        value: dpg-d43885ngi27c73frpdqg-a.oregon-postgres.render.com
      - key: POSTGRES_PORT
        value: 5432
      - key: POSTGRES_DB
        value: cupertino_db
      - key: POSTGRES_USER
        value: cupertino_db_user
      - key: POSTGRES_PASSWORD
        value: uijK11v8v1jwDSyyOlOHxvmmiynpMLx1
      - key: POSTGRES_TLS
        value: require
